repos:
  - repo: 'https://github.com/PyCQA/isort'
    rev: 5.9.1
    hooks:
      - id: isort
        language_version: python3.9
        exclude: ^(migrations|test|postman)/
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types:
          - python
        args:
          - '--load-plugins'
          - pylint_mongoengine
        exclude: ^(migrations|test|postman)/
  - repo: 'https://github.com/psf/black'
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3.9
        exclude: ^(migrations|test|postman)/
  - repo: 'https://github.com/pre-commit/mirrors-mypy'
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies:
          - types-toml
        language_version: python3.9
        exclude: ^(migrations|test|postman)/
  - repo: 'https://github.com/PyCQA/bandit'
    rev: 1.7.0
    hooks:
      - id: bandit
        exclude: ^(migrations|test|postman)/
